
#ifndef _INCLUDE_CREDENTIALS_HPP_
#define _INCLUDE_CREDENTIALS_HPP_

#define MQTT_BROKER_ADDRESS "mqtt://192.168.178.29:1883"
#define MQTT_USERNAME "YourMQTTUsername"
#define MQTT_PASSWORD "YourMQTTPassword"

#endif // _INCLUDE_CREDENTIALS_HPP_